### ISSUE TITLE
请问如何引用哈工大的停用词表啊？

### ISSUE THREAD

**Issue by bright1993ff66** [goto456/stopwords#4]
可以引用哪篇文章？最好给出来一个bibtex
多谢哈 🥰

**Comment by allenXu317** [comment]
hello，基本思路就是引用停用词表的.txt文件，程序运行中生成列表，然后判断所分词是否在停用词列表中。
具体可参考：
https://blog.csdn.net/qq_36090423/article/details/88040557

**Comment by bright1993ff66** [comment]
> hello，基本思路就是引用停用词表的.txt文件，程序运行中生成列表，然后判断所分词是否在停用词列表中。
> 具体可参考：
> https://blog.csdn.net/qq_36090423/article/details/88040557

谢谢你的回复！我可能没表达清楚，我目前在写文章，想要用这个停用词表，请问要引用哪篇citation呢？会议还是期刊？

**Comment by allenXu317** [comment]
> > hello，基本思路就是引用停用词表的.txt文件，程序运行中生成列表，然后判断所分词是否在停用词列表中。
> > 具体可参考：
> > https://blog.csdn.net/qq_36090423/article/details/88040557
> 
> 谢谢你的回复！我可能没表达清楚，我目前在写文章，想要用这个停用词表，请问要引用哪篇citation呢？会议还是期刊？

嗯嗯，我没理解清楚，我觉得可以参考这篇文章：
https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFQ&dbname=CJFDLAST2017&filename=XDTQ201703013&v=MDc1MjBlWDFMdXhZUzdEaDFUM3FUcldNMUZyQ1VSN3FmWU9ab0ZpRGxVTHZNUFNuZmY3RzRIOWJNckk5RVo0Ujg=
他采用了多个分词表，你可以看它的引文怎么写的。

**Comment by bright1993ff66** [comment]
> > > hello，基本思路就是引用停用词表的.txt文件，程序运行中生成列表，然后判断所分词是否在停用词列表中。
> > > 具体可参考：
> > > https://blog.csdn.net/qq_36090423/article/details/88040557
> > 
> > 
> > 谢谢你的回复！我可能没表达清楚，我目前在写文章，想要用这个停用词表，请问要引用哪篇citation呢？会议还是期刊？
> 
> 嗯嗯，我没理解清楚，我觉得可以参考这篇文章：
> https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFQ&dbname=CJFDLAST2017&filename=XDTQ201703013&v=MDc1MjBlWDFMdXhZUzdEaDFUM3FUcldNMUZyQ1VSN3FmWU9ab0ZpRGxVTHZNUFNuZmY3RzRIOWJNckk5RVo0Ujg=
> 他采用了多个分词表，你可以看它的引文怎么写的。

哇塞好的！多谢
